<?php
use yii\helpers\Html;
$this->title=$model->arc_nombre_documento ?: $model->arc_codigo;
$this->params['breadcrumbs'][]=['label'=>'Documentos','url'=>['index']]; $this->params['breadcrumbs'][]=$this->title;
$location=$model->arcCaja ? implode(' · ',array_filter([$model->arcCaja->caj_codigo,$model->arcCaja->cajAnaquel->ana_nombre??null,$model->arcCaja->cajNivel->niv_nombre??null])) : 'Sin ubicación asignada';
?>
<div class="d-flex flex-wrap justify-content-between gap-3 page-heading"><div><h1><?= Html::encode($this->title) ?></h1><p><?= Html::encode($model->arc_codigo) ?><?= $model->arcAlumno?' · '.Html::encode($model->arcAlumno->alu_matricula):'' ?></p></div><div><?php if(Yii::$app->user->can('archivo.localizar')): ?><?= Html::a('Localizar',['/busqueda/localizar','arc_id'=>$model->arc_id],['class'=>'btn btn-primary']) ?><?php endif ?> <?php if(Yii::$app->user->can('archivo.descargar')): ?><?= Html::a('Descargar',['download','id'=>$model->arc_id],['class'=>'btn btn-outline-primary']) ?><?php endif ?> <?php if(Yii::$app->user->can('archivo.editar')): ?><?= Html::a('Editar',['update','arc_id'=>$model->arc_id],['class'=>'btn btn-outline-secondary']) ?><?php endif ?></div></div>
<div class="row g-3"><div class="col-lg-7"><section class="card mb-3"><div class="card-body"><h2 class="h5">Información documental</h2><dl class="row mb-0"><dt class="col-sm-4">Documento</dt><dd class="col-sm-8"><?= Html::encode($model->arc_nombre_documento) ?></dd><dt class="col-sm-4">Código clasificador</dt><dd class="col-sm-8"><?= Html::encode($model->arc_codigo) ?></dd><dt class="col-sm-4">Clasificación</dt><dd class="col-sm-8"><?= Html::encode(implode(' → ',array_filter([$model->arcFondo->fon_descripcion??null,$model->arcSeccionSerie->sec_descripcion??null,$model->arcAreaGeneradora->are_descripcion??null,$model->arcClaveProgramatica->cla_descripcion??null]))) ?: 'Sin clasificación completa' ?></dd></dl></div></section><section class="card"><div class="card-body"><h2 class="h5">Alumno</h2><?php if($model->arcAlumno): ?><p class="mb-1"><strong><?= Html::encode($model->arcAlumno->getNombreCompleto()) ?></strong></p><p class="text-muted mb-0"><?= Html::encode($model->arcAlumno->alu_matricula) ?><?= $model->arcAlumno->aluCarrera?' · '.Html::encode($model->arcAlumno->aluCarrera->car_nombre):'' ?></p><?php else: ?><p class="text-muted mb-0">No hay alumno asociado.</p><?php endif ?></div></section></div><div class="col-lg-5"><section class="card mb-3"><div class="card-body"><h2 class="h5">Archivo físico</h2><p class="mb-0"><?= Html::encode($location) ?></p></div></section><section class="card"><div class="card-body"><h2 class="h5">Documento digital</h2><p class="text-muted">El PDF está resguardado en el sistema.</p><?php if(Yii::$app->user->can('archivo.descargar')): ?><?= Html::a('Descargar PDF',['download','id'=>$model->arc_id],['class'=>'btn btn-outline-primary']) ?><?php endif ?></div></section></div></div>
<?php if(Yii::$app->user->can('archivo.eliminar')): ?><div class="mt-4 pt-3 border-top text-end"><?= Html::a('Eliminar documento',['delete','arc_id'=>$model->arc_id],['class'=>'btn btn-sm btn-outline-danger','data'=>['confirm'=>'Eliminar '.$model->arc_codigo.' — '.$model->arc_nombre_documento.'. Se eliminará el registro y el PDF asociado.','method'=>'post']]) ?></div><?php endif ?>
