<?php
use yii\helpers\Html;
$isSuperior = app\components\RbacAccess::role() === 'adminsuperior';
?>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 page-heading"><div><h1><?= $isSuperior ? 'Supervisión del sistema' : 'Gestión documental' ?></h1><p><?= $isSuperior ? 'Alertas y accesos de gobierno, separados de la operación diaria.' : 'Trabajo pendiente y actividad documental reciente.' ?></p></div><div><?= Html::a('Registrar documento',['/archivo/create'],['class'=>'btn btn-primary']) ?> <?= Html::a('Nueva carga',['/carga-masiva/create'],['class'=>'btn btn-outline-primary']) ?></div></div>
<div class="row g-3 mb-4">
 <?php foreach ([['Pendientes de revisión',$metrics['pendientes'],'warning'],['Errores de procesamiento',$metrics['errores'],'danger'],['Documentos registrados',$metrics['archivos'],'primary'],['Cajas físicas',$metrics['cajas'],'secondary']] as [$label,$value,$color]): ?><div class="col-6 col-lg-3"><div class="card h-100"><div class="card-body"><div class="text-muted small"><?= Html::encode($label) ?></div><div class="fs-2 fw-semibold text-<?= $color ?>"><?= Html::encode($value) ?></div></div></div></div><?php endforeach ?>
</div>
<div class="row g-3"><div class="col-lg-7"><div class="card h-100"><div class="card-header bg-white"><strong>Cargas recientes</strong></div><div class="list-group list-group-flush"><?php if(!$recentLoads): ?><div class="list-group-item text-muted">Aún no hay cargas registradas.</div><?php endif ?><?php foreach($recentLoads as $load): ?><a class="list-group-item list-group-item-action d-flex justify-content-between" href="<?= yii\helpers\Url::to(['/carga-masiva/view','id'=>$load->car_id]) ?>"><span>Caja <?= Html::encode($load->caja->caj_codigo ?? 'sin asignar') ?></span><span><?= Html::encode($load->car_pendientes) ?> pendientes</span></a><?php endforeach ?></div></div></div><div class="col-lg-5"><div class="card h-100"><div class="card-header bg-white"><strong>Requiere atención</strong></div><div class="card-body"><?php if(!$metrics['pendientes'] && !$metrics['errores']): ?><p class="mb-0 text-success">Todo el procesamiento está al día.</p><?php else: ?><p>Hay <?= Html::encode($metrics['pendientes']) ?> documentos por revisar y <?= Html::encode($metrics['errores']) ?> sin procesar.</p><?= Html::a('Revisar cargas',['/carga-masiva/index'],['class'=>'btn btn-outline-primary']) ?><?php endif ?><?php if($isSuperior): ?><hr><?= Html::a('Administración del sistema',['/admin'],['class'=>'btn btn-outline-dark']) ?><?php endif ?></div></div></div></div>
